name: Run test workflow
on:
  workflow_dispatch:
    inputs:
      refToBuild:
        description: "Commit SHA to build"
        required: true
        type: string

env:
  PROJECT_ID: Test project

jobs:
  run_workflow:
    name: Run workflow
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.refToBuild }}

      - name: "Print Input"
        run: |
          echo ${{ inputs.refToBuild }}
